remote_theme: zerostaticthemes/jekyll-serif-theme
timezone: Europe/Berlin
incremental: TRUE

email: aron@petau.net
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the home of reprinted, the place for all updates around my filament
  recycling project and distantly related things happening around me.
  Take a look around!

baseurl: "/reprinted/"

paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


social: # jekyll-seo-tag > social overrides
  name: Aron Petau # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/share0n
    - https://www.linkedin.com/in/aronpetau
    - https://github.com/arontaupe

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: About
  url: /about/
- title: Privacy
  url: /privacy/
